### ISSUE TITLE
cmdline flag for releaseInstallPath

### ISSUE THREAD

**Issue by yermulnik** [maratoid/gh-install#1]
Would be cool to have a flag for `releaseInstallPath` too to allow customizing installation destination path. Thanks.

**Comment by maratoid** [comment]
> Would be cool to have a flag for `releaseInstallPath` too to allow customizing installation destination path. Thanks.

Hi! Thanks for trying out the extension. I think that would be a good thing to add, I'll work on it - meantime you should be able to set the `GH_INSTALL_ENV_PATH` environment variable to override the default installation destination.

**Comment by maratoid** [comment]
Added in https://github.com/maratoid/gh-install/pull/2

**Comment by yermulnik** [comment]
Thank you 👍🏻
